<a href="https://colab.research.google.com/github/Martine1grace/NLP_FELLOWSHIP_AI-Machine_Translation.-/blob/main/week6/NeuralNetwork_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [8]:
#Load the dtaset using pandas
import pandas as pd
import requests

df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')
df.to_csv('pima.csv')

response = requests.get('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')

with open('pima_r.csv', 'w+') as file:
  file.write(response.text)

In [13]:
#load the data( .csv=',' & .tsv='\t')
dataset = loadtxt('/content/pima_r.csv', delimiter=',')
#split
x = dataset[:,0:8]
y = dataset[:,8]

#######

In [11]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [14]:
import numpy as np
df_x = np.array(df.iloc[:,0:8].astype(int))
df_y = np.array(df.iloc[:,8].astype(int))

In [15]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [16]:
df_x

array([[  1,  85,  66, ...,  26,   0,  31],
       [  8, 183,  64, ...,  23,   0,  32],
       [  1,  89,  66, ...,  28,   0,  21],
       ...,
       [  5, 121,  72, ...,  26,   0,  30],
       [  1, 126,  60, ...,  30,   0,  47],
       [  1,  93,  70, ...,  30,   0,  23]])

In [17]:
y


array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [18]:
df_y

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,

In [24]:
#Dfine the keras model
model = Sequential()
model.add(Dense(12,input_shape=(8,),activation='relu')) #input layers
#hidden layer
model.add(Dense(8,activation='relu'))
model.add(Dense(6, activation='relu'))
#end of hidden layer
model.add(Dense(1,activation='sigmoid'))#output layers

In [25]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [26]:
model.fit(x,y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 2.4599 - accuracy: 0.5729
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.4429 - accuracy: 0.5872
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1893 - accuracy: 0.6029
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0378 - accuracy: 0.6016
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0015 - accuracy: 0.6068
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9326 - accuracy: 0.6042
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8545 - accuracy: 0.6042
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8076 - accuracy: 0.6328
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7663 - accuracy: 0.6510
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8169 - accuracy: 0.6016
Epoch 11/

In [27]:
_, accuracy = model.evaluate(x, y)
print(accuracy)

24/24 [==============================] - 0s 2ms/step - loss: 0.4772 - accuracy: 0.7669
0.7669270634651184
